### ISSUE TITLE
Constructor with frequency parameter doesn't work

### ISSUE THREAD

**Issue by FOp42** [Naguissa/uMuxOutputLib#2]
If I try to set the multiplex frequency, the object doesn't work at all because _nmuxes contains 0 instead of the given parameter nmuxes. Calling one constructor from the other doesn't seem to work as expected. 
Others gave me this hints:
You create a nameless local object of type uMuxOutputLib in your constructor
uMuxOutputLib, which is then immediately destroyed again. This local
Object has nothing to do with the first. So the parameters all end up
in Nirvana.
Please try member initialization and delegating constructor. This is how you do it from C++11.

**Comment by FOp42** [comment]
It should be possible to set a default value for the parameter frequency to have only one constructor instead of two while keeping the behavior to the user like described.

**Comment by FOp42** [comment]
[proposal.zip](https://github.com/Naguissa/uMuxOutputLib/files/13854501/proposal.zip)

**Comment by Naguissa** [comment]
Thanks for the report and proposal.

What IDE/Compiler and board are you using?

I tested it several months ago with Arduino IDE and few boards and I didn-t faced that problem< I-ll retest it again.


Cheers!

**Comment by FOp42** [comment]
Software used :
- Arduino AVR Boards version 1.8.6 from Arduino
  uses g++ version 7.3.0 in path avr-gcc\7.3.0-atmel3.6.1-arduino7
- library uMuxOutputLib version 1.0.2
- library uTimerLib version 1.7.2
- Arduino IDE version 2.2.1
- Windows 11 Pro 64 bit version 23H2 22631.2861

Board selected :
- Arduino pro mini

**Comment by Naguissa** [comment]
Solved on new 1.0.3 release: https://github.com/Naguissa/uMuxOutputLib/releases

Thanks for reporting.
